#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubirImagenesClientes
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hospital")]
	public partial class CochesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCoch(Coch instance);
    partial void UpdateCoch(Coch instance);
    partial void DeleteCoch(Coch instance);
    #endregion
		
		public CochesDataContext() : 
				base(global::SubirImagenesClientes.Properties.Settings.Default.HospitalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CochesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CochesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CochesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CochesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Coch> Coches
		{
			get
			{
				return this.GetTable<Coch>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Coches")]
	public partial class Coch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCoche;
		
		private string _Imagen_Coche;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCocheChanging(int value);
    partial void OnIdCocheChanged();
    partial void OnImagen_CocheChanging(string value);
    partial void OnImagen_CocheChanged();
    #endregion
		
		public Coch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCoche", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCoche
		{
			get
			{
				return this._IdCoche;
			}
			set
			{
				if ((this._IdCoche != value))
				{
					this.OnIdCocheChanging(value);
					this.SendPropertyChanging();
					this._IdCoche = value;
					this.SendPropertyChanged("IdCoche");
					this.OnIdCocheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen_Coche", DbType="NVarChar(50)")]
		public string Imagen_Coche
		{
			get
			{
				return this._Imagen_Coche;
			}
			set
			{
				if ((this._Imagen_Coche != value))
				{
					this.OnImagen_CocheChanging(value);
					this.SendPropertyChanging();
					this._Imagen_Coche = value;
					this.SendPropertyChanged("Imagen_Coche");
					this.OnImagen_CocheChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
